In [31]:
import numpy as np

In [32]:
x, y = [], []

data = open('hw1_15_train.dat', 'r')
for line in data.readlines():
    example = list(map(float, line.split()))
    example.insert(0, 1.0)
    x.append(example[:5])
    y.append(int(example[5]))
data.close()

x = np.array(x)
y = np.array(y)
for i in range(5):
    print(x[i], y[i])

[1.      0.97681 0.10723 0.64385 0.29556] 1
[1.      0.67194 0.2418  0.83075 0.42741] 1
[1.      0.20619 0.23321 0.81004 0.98691] 1
[1.       0.51583  0.055814 0.92274  0.75797 ] 1
[1.      0.70893 0.10836 0.33951 0.77058] 1


In [33]:
def sign(x):
    result = -1
    if x > 0:
        result = 1
    return result

In [34]:
def pla(seed):
    w = np.zeros(5)
    i, times = 0, 0
    correct = 0
    total = y.size
    
    np.random.seed(seed)
    x_random = np.random.permutation(x)
    np.random.seed(seed)
    y_random = np.random.permutation(y)
    
    while correct != total:
        if sign(np.dot(w, x_random[i].T)) != y_random[i]:
            w = w + y_random[i] * x_random[i] * 0.5
            correct = 0
            times = times + 1
        i = (i + 1) % total
        correct = correct + 1 

    return w, times

In [36]:
average = 0
for i in range(2000):
    w, times = pla(i)
    #print(i, w, times)
    average = average + times
print(average / 2000)

40.0125
